---
# tasks file for ssh_keygen
- name: check .ssh/id_rsa
  shell: test -f {{ key }}
  ignore_errors: True
  register: keygend
  tags:
    - ssh_keygen

- name: setup ssh-keygen
  shell: ssh-keygen -q -t rsa -N {{ ssh_passphrase }} -f {{ key }}
  when: keygend.rc != 0
  tags:
    - ssh_keygen
