---
- name: install packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - python
    - python-pip
    - python-apt
    - python-pycurl
    - python-paramiko
    - python-yaml
    - python-jinja2
    - python-httplib2
    - python-passlib
  tags:
    - ansible

- name: add apt repository
  sudo: yes
  apt_repository: repo='ppa:rquillo/ansible' state=present
  tags:
    - ansible

- name: install ansible
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - ansible
  tags:
    - ansible
