---
- name: install packages
  sudo: yes
  apt: name=tmux state=latest
  tags:
    - tmux

- name: Download tmux-completion
  sudo: yes
  get_url: |
    url='{{ tmux_compl_url }}'
    dest='{{ tmux_compl }}'
  tags:
    - tmux
