---
- name: add apt repository
  sudo: yes
  apt_repository: repo='ppa:mizuno-as/silversearcher-ag' state=present
  when: >
    ansible_distribution == 'Debian'
        and ansible_distribution_version.split('.')[0]|int >= 13
  tags:
    - ag

- name: install ansible
  sudo: yes
  apt: name=silversearcher-ag state=latest update_cache=yes
  when: >
    ansible_distribution == 'Debian'
        and ansible_distribution_version.split('.')[0]|int >= 13
  tags:
    - ag
